version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/merge-sort-api
hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: root      
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: root      