version: "3"
services:
 merge-sort:
  # image: merge-sort  
  build:
    context: ./
    dockerfile: Dockerfile      
  container_name: merge-sort-app
  ports:
   - "3000:3000"
  environment:
   - TZ=America/Tijuana  
   - PORT=3000 
  network_mode: bridge