---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merge-sort-site
  namespace: default
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: merge-sort-app
          image: elliotmtz12/merge-sort
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Tijuana
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
      nodeSelector:
        env: prod            
