---
apiVersion: v1
kind: Pod
metadata:
  name: merge-sort-pod
  labels:
    app: web
spec:
  containers:
    - name: merge-sort-app
      image: merge-sort
      imagePullPolicy: Never
      env:
        - name: TZ
          value: America/Tijuana
        - name: PORT
          value: 8080          
      ports:
        - containerPort: 8080